### ISSUE TITLE
Trying to install on Linux with a venv

### ISSUE THREAD

**Issue by avalon60** [dishb/hive#1]
Hi @dishb. Having commented out the MacOS trap, to allow me to install on Linux Mint, I find that I get this:

`source venv/bin/activate`

```
python3 utility/build.py
Unable to find "/home/clive/PycharmProjects/hive/config" when adding binary and data files.
```

**Comment by dishb** [comment]
Thanks for reporting this issue! :)

The issue is that in the build script, I use Pyinstaller. The build script is the exact same as running Pyinstaller through the CLI. One of the options I've given Pyinstaller is to add a directory named `config`. When you first clone the project, that directory doesn't exist until the app has been run at least once.

The solution I'm adding right now is a simple check (with `os.path.exists`) to see if the `config` directory exists. If it doesn't, we won't include the option in the Pyinstaller build command.
