### ISSUE TITLE
Cross-platform support (with paths)

### ISSUE THREAD

**Issue by avalon60** [dishb/hive#2]
Not so much an issue, but in the absence of a discussions forum, I thought that I would suggest this here.

Before you end up with a bigger and bigger project, you might want to start thinking about the Windows paths. This entails using the following import:

`from pathlib import Path`

This allows you to treat all Paths in the same way. Say you have a directory "/home/dishb". You can convert it to a Path object like this:

`home_dir = Path("/home/dishb")`

Once you do this, you can manipulate Path objects like this:

`hive_dir = home_dir / "hive"`

This then automatically works for Windows, since pathlib does all the platform specific work for you (converting between fwd and backwards slashes etc).

It comes with other benefits too. For example if you want to know if hive_dir exists, you can simply do something like:

```
if hive_dir.exists():
  do_whatever...
```

Which I think, is much nicer than:

```
if os.path.exists(hive_dir):
  do-whatever...
```
Anyway, if you tackle this sooner rather than later, you'll have less technical debt to work through.
 You can read more [here](https://realpython.com/python-pathlib/).

**Comment by dishb** [comment]
Will begin work on adding better paths with `pathlib.Path()`. 

I'll then look at #3

**Comment by dishb** [comment]
This will be much harder than expected. Due to the way I'm using file paths in `customtkinter.StringVars()`, displaying the file paths, as well as the numerous other places in `./core/file_explorer.py` where I use file paths. 

From being a macOS-only file explorer, we're going cross-platform!

**Comment by dishb** [comment]
I don't think I'll be continuing with the `pathlib.Path()` migration. I've made this decision for a few reasons:

- `hive` was not intended to be cross-platform, but rather specifically for macOS.
- The migration from strings to `Path()` (basically making the project cross-platform) would break many features.
- Apart from the bugs that cannot be fixed, the "system files" feature would be deleted as it requires indexing every single hidden file/directory on a given OS.
- While not exactly a reason to continue with the migration, this reason is a deterrent: this is a massive task requiring an overhaul of how `StringVar()` is used throughout the codebase.
- As a file explorer, the whole codebase revolves around paths. Strings are simply easier to use and work with, however the migration would introduce a large amount of bugs/issues.
- Linux support _may_ or _may not_ be added because it too, like macOS, is a UNIX-like OS.
- Many resources (icons, themes, config files) are accessed through unconventional ways that wouldn't work with the `Path()` object.
- Cross-platform was never a goal at the start of the project. While this means more potential users, it's just not something I think is necessary for this project.
- Cross-platform _might_ help the project expand, but at its current (small, relatively unknown) state, I don't think cross-platform is worth it.
- The build script will be left using `pathlib.Path()` This means users on Windows, Linux, and macOS can build `hive`. However, there are no guarantees for Windows users or Linux. If it works on Linux, that's great! But do note it wasn't intentionally designed to work on Linux. Some distros are different.
- Some may say the above point means inconsistency in the codebase, but I feel that it is a minor inconsistency and doesn't warrant change. It's also a little dumb to revert a change that doesn't introduce any bugs.
- A migration to `pathlib.Path()` and cross-platform would mean changing the about section and description of `hive` which goes to say that maybe cross-platform isn't for this project.
- The Windows file system is much more complex than the macOS file system. With multiple drives and backslashes ("\"), it's just more complex and therefore harder to implement.
- Due to the project being open-source, anyone can create a fork _specifically_ designed for Windows. I was planning on doing this until I realized I don't have a Windows machine.
